name: mario_socrates
favicon: null
layout_spectrum: 0.01906
typography_spectrum: 0.5845548149663955
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bfbfbf'
    - '#e7e7e7'
    - '#4a4a4a'
    - '#808080'
    - '#1f1f1f'
  brandStrength: 0.5
  lightness: 0.11778582143597305
  saturation: 0.7796862737741321
  rhythmicContrast: 0.6329592720139772
purpose: []
