name: mario_socrates
favicon: null
layout_spectrum: 0.01906
typography_spectrum: 0.5845548149663955
title: mariosocratesphotography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#adc661'
    - '#280446'
    - '#fd8b25'
    - '#88480f'
  brandStrength: 0.5
  lightness: 0.11778582143597305
  saturation: 0.7796862737741321
  rhythmicContrast: 0.6329592720139772
purpose: []
